version: "3.2"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: keycloak
    ports:
      - "9900:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
    volumes:
     - keycloak_data:/data
     - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json


volumes:
  keycloak_data:
